# Generated by Django 5.0.2 on 2024-04-24 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user1", "0002_myorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorder",
            name="o_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
