# Generated by Django 5.0.2 on 2024-04-26 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user1", "0003_myorder_o_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flavourpaan",
            name="orders",
        ),
        migrations.RemoveField(
            model_name="paanaroma",
            name="orders",
        ),
        migrations.RemoveField(
            model_name="specialpaan",
            name="orders",
        ),
        migrations.RemoveField(
            model_name="sweetpaan",
            name="orders",
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=1000)),
                ("query", models.CharField(max_length=5000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
