# Generated by Django 5.0.2 on 2024-05-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user1", "0005_myorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="myorder",
            name="p_deliverytime",
            field=models.CharField(default="", max_length=100),
        ),
    ]
